# Stanford Library Makefile in final dir

SOURCE = ..\number3
INCLUDE = -I.\include -I..\ProfEx
LIBS = -L.\lib
LINKS = -lStanford64 -limagehlp
all:
	g++ $(SOURCE).cpp -o $(SOURCE).exe $(INCLUDE) $(LIBS) $(LINKS)