# Makefile for number 4 of chapter 5 (from homework 2)
PRIMESOURCE = number4test
EXTRASOURCE = ..\..\ch4\number9.cpp ..\number4.cpp
INCLUDE = -I.\include -I..\..\ch4
LIBS = -L.\lib
LINKS = -lStanford64 -limagehlp
all:
	g++ ..\$(PRIMESOURCE).cpp $(EXTRASOURCE) -o ..\number4.exe $(INCLUDE) $(LIBS) $(LINKS)