# Stanford Library Makefile in stafnlib dir for hw3

SOURCE = ..\ch5\number12
INCLUDE = -I.\include
LIBS = -L.\lib
LINKS = -lStanford64 -limagehlp
all:
	g++ $(SOURCE).cpp -o $(SOURCE).exe $(INCLUDE) $(LIBS) $(LINKS)